site :opscode

cookbook 'apache2'
cookbook 'apt'
cookbook 'build-essential'
cookbook 'readline'
cookbook 'openssh'
cookbook 'perl'
cookbook 'xml'
cookbook 'nodejs'
cookbook 'zlib'
cookbook 'memcached'
cookbook 'mysql'
cookbook 'openssl'
cookbook 'php'
cookbook 'postfix'
cookbook 'misc',
	path: 'cookbooks/misc'
cookbook 'rvm',
	git: 'https://github.com/fnichol/chef-rvm.git'
cookbook 'chef-dotdeb',
	git: 'https://github.com/homemade/chef-dotdeb.git'
